### ISSUE TITLE
Hard coded windows path

### ISSUE THREAD

**Issue by ravi5175** [FreshlyBuilt/freshlybuiltimagebol#17]
Freshlybuiltimagebol library file OCR_Printed_Text.py contains hard coded Microsoft Windows OS filesystem path. hence while implementing it cause an issue where it keeps searching for .exe extension file even in linux based distros

Hope this issue will be solved as soon as possible 

![unknown](https://user-images.githubusercontent.com/48784560/88694684-7b88ac00-d11e-11ea-8a09-757c83f910f2.png)

**Comment by KapilBansal320** [comment]
I will fix it in sometime wait
